/*
 * Copyright 2026 Revetware LLC.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.revetsec.oidc;

import com.google.errorprone.annotations.CheckReturnValue;

import org.jspecify.annotations.NonNull;
import org.jspecify.annotations.Nullable;
import javax.annotation.concurrent.Immutable;
import javax.annotation.concurrent.NotThreadSafe;
import java.net.URI;
import java.time.Duration;
import java.util.*;
import static java.util.Objects.requireNonNull;
import com.revetsec.oauth.AuthorizationRequestOptions;

/**
 * Per-login OIDC options (OpenID Connect Core section 3.1.2.1). Complete scope/resource and ACR sets replace defaults.
 * Nonce is generated by the client. Requested max-age and ACR values are authenticated in pending state and enforced
 * on the ID token. Application data still needs application redirect allowlisting.
 *
 * @author <a href="https://www.revetkn.com">Mark Allen</a>
 * @since 1.0.0
 */
@Immutable
public final class OidcAuthenticationOptions {
	private final AuthorizationRequestOptions oauth;
	private final @Nullable Set<String> scopes;
	private final @Nullable List<URI> resources;
	private final @Nullable Set<String> acrValues;
	private final @Nullable Duration maxAge;
	private OidcAuthenticationOptions(Builder builder) {
		this.oauth = builder.oauth.build(); this.scopes = builder.scopes; this.resources = builder.resources;
		this.acrValues = builder.acrValues; this.maxAge = builder.maxAge;
	}
	/**
	 * Starts login options with no per-request overrides.
	 *
	 * @return the builder
	 * @since 1.0.0
	 */
	public static @NonNull Builder builder() { return new Builder(); }
	/**
	 * Returns the maximum authentication age.
	 *
	 * @return maximum authentication age
	 * @since 1.0.0
	 */
	public @NonNull Optional<@NonNull Duration> getMaxAge() { return Optional.ofNullable(this.maxAge); }
	/**
	 * Returns the ACR override.
	 *
	 * @return ACR override
	 * @since 1.0.0
	 */
	public @NonNull Optional<@NonNull Set<@NonNull String>> getRequiredAcrValues() { return Optional.ofNullable(this.acrValues); }
	/**
	 * Returns the scope override.
	 *
	 * @return scope override
	 * @since 1.0.0
	 */
	public @NonNull Optional<@NonNull Set<@NonNull String>> getScopes() { return Optional.ofNullable(this.scopes); }
	/**
	 * Returns the resource override.
	 *
	 * @return resource override
	 * @since 1.0.0
	 */
	public @NonNull Optional<@NonNull List<@NonNull URI>> getResources() { return Optional.ofNullable(this.resources); }
	/**
	 * Returns the prompt.
	 *
	 * @return prompt
	 * @since 1.0.0
	 */
	public @NonNull Optional<@NonNull String> getPrompt() { return this.oauth.getPrompt(); }
	/**
	 * Returns the login hint.
	 *
	 * @return login hint
	 * @since 1.0.0
	 */
	public @NonNull Optional<@NonNull String> getLoginHint() { return this.oauth.getLoginHint(); }
	/**
	 * Returns the application data.
	 *
	 * @return application data
	 * @since 1.0.0
	 */
	public @NonNull Map<@NonNull String, @NonNull String> getApplicationData() { return this.oauth.getApplicationData(); }
	AuthorizationRequestOptions transactionOptions(Set<String> defaults, List<URI> defaultResources) {
		Set<String> requested = new HashSet<>(this.scopes == null ? defaults : this.scopes);
		requested.add("openid");
		return AuthorizationRequestOptions.builder().scopes(requested)
				.resources(this.resources == null ? defaultResources : this.resources).responseMode(this.oauth.getResponseMode())
				.prompt(this.oauth.getPrompt().orElse(null)).loginHint(this.oauth.getLoginHint().orElse(null))
				.applicationData(this.oauth.getApplicationData()).additionalParameters(this.oauth.getAdditionalParameters()).build();
	}
	static Set<String> requireAcrValues(Set<String> values) {
		Set<String> copy = Set.copyOf(values);
		if (copy.stream().anyMatch(value -> value.isEmpty() || value.chars().anyMatch(c -> c <= 0x20 || c >= 0x7F)))
			throw new IllegalArgumentException("An ACR value contains invalid characters.");
		return copy;
	}
	/**
	 * Redacts request options.
	 *
	 * @return a redacted description
	 * @since 1.0.0
	 */
	@Override public @NonNull String toString() { return "OidcAuthenticationOptions{options=<redacted>}"; }
	/**
	 * Mutable per-login option builder.
	 * @author <a href="https://www.revetkn.com">Mark Allen</a>
	 * @since 1.0.0
	 */
	@NotThreadSafe
	@CheckReturnValue
	public static final class Builder {
		private AuthorizationRequestOptions.Builder oauth = AuthorizationRequestOptions.builder();
		private @Nullable Set<String> scopes;
		private @Nullable List<URI> resources;
		private @Nullable Set<String> acrValues;
		private @Nullable Duration maxAge;
		private Builder() { }
		/**
		 * Sets the complete scope override. Null restores the default.
		 *
		 * @param value the value, or null
		 * @return this builder
		 * @since 1.0.0
		 */
		public @NonNull Builder scopes(@Nullable Set<@NonNull String> value) { this.scopes = value == null ? null : AuthorizationRequestOptions.builder().scopes(value).build().getScopes(); return this; }
		/**
		 * Sets the ordered resource override. Null restores the default.
		 *
		 * @param value the value, or null
		 * @return this builder
		 * @since 1.0.0
		 */
		public @NonNull Builder resources(@Nullable List<@NonNull URI> value) { this.resources = value == null ? null : AuthorizationRequestOptions.builder().resources(value).build().getResources(); return this; }
		/**
		 * Sets the complete accepted ACR override. Null restores the default.
		 *
		 * @param value the value, or null
		 * @return this builder
		 * @since 1.0.0
		 */
		public @NonNull Builder requiredAcrValues(@Nullable Set<@NonNull String> value) { this.acrValues = value == null ? null : requireAcrValues(value); return this; }
		/**
		 * Sets the maximum authentication age; zero still requires auth_time. Null restores the default.
		 *
		 * @param value the value, or null
		 * @return this builder
		 * @since 1.0.0
		 */
		// The nanosecond adjustment is deliberately checked: the wire value must be whole seconds.
		@SuppressWarnings("JavaDurationGetSecondsGetNano")
		public @NonNull Builder maxAge(@Nullable Duration value) { if (value != null && (value.isNegative() || value.getNano() != 0)) throw new IllegalArgumentException("Maximum authentication age must be whole non-negative seconds."); this.maxAge = value; return this; }
		/**
		 * Sets the Core prompt values; none must be used alone. Null restores the default.
		 *
		 * @param value the value, or null
		 * @return this builder
		 * @since 1.0.0
		 */
		public @NonNull Builder prompt(@Nullable String value) { if (value != null) { List<String> prompts = List.of(value.split(" ", -1)); if (prompts.stream().anyMatch(p -> !Set.of("none", "login", "consent", "select_account").contains(p)) || Set.copyOf(prompts).size() != prompts.size() || (prompts.contains("none") && prompts.size() != 1)) throw new IllegalArgumentException("The OIDC prompt is invalid."); } this.oauth = this.oauth.prompt(value); return this; }
		/**
		 * Sets the login hint. Null restores the default.
		 *
		 * @param value the value, or null
		 * @return this builder
		 * @since 1.0.0
		 */
		public @NonNull Builder loginHint(@Nullable String value) { this.oauth = this.oauth.loginHint(value); return this; }
		/**
		 * Sets the complete application data. Null restores the default.
		 *
		 * @param value the value, or null
		 * @return this builder
		 * @since 1.0.0
		 */
		public @NonNull Builder applicationData(@Nullable Map<@NonNull String, @NonNull String> value) { this.oauth = this.oauth.applicationData(value == null ? Map.of() : value); return this; }
		/**
		 * Sets the complete nonreserved authorization parameters. Null restores the default.
		 *
		 * @param value the value, or null
		 * @return this builder
		 * @since 1.0.0
		 */
		public @NonNull Builder additionalParameters(@Nullable Map<@NonNull String, @NonNull String> value) { this.oauth = this.oauth.additionalParameters(value == null ? Map.of() : value); return this; }
		/**
		 * Sets callback delivery. Null restores query delivery.
		 *
		 * @param value mode, or null
		 * @return this builder
		 * @since 1.0.0
		 */
		public @NonNull Builder responseMode(AuthorizationRequestOptions.@Nullable ResponseMode value) { this.oauth = this.oauth.responseMode(value == null ? AuthorizationRequestOptions.ResponseMode.QUERY : value); return this; }
		/**
		 * Builds immutable login options.
		 *
		 * @return the options
		 * @since 1.0.0
		 */
		public @NonNull OidcAuthenticationOptions build() { return new OidcAuthenticationOptions(this); }
	}
}
